#ifndef GUARD_CONSTANTS_SPECIES_H
#define GUARD_CONSTANTS_SPECIES_H

#define SPECIES_NONE 0
#define SPECIES_BULBASAUR 1
#define SPECIES_IVYSAUR 2
#define SPECIES_VENUSAUR 3
#define SPECIES_CHARMANDER 4
#define SPECIES_CHARMELEON 5
#define SPECIES_CHARIZARD 6
#define SPECIES_SQUIRTLE 7
#define SPECIES_WARTORTLE 8
#define SPECIES_BLASTOISE 9
#define SPECIES_CATERPIE 10
#define SPECIES_METAPOD 11
#define SPECIES_BUTTERFREE 12
#define SPECIES_WEEDLE 13
#define SPECIES_KAKUNA 14
#define SPECIES_BEEDRILL 15
#define SPECIES_PIDGEY 16
#define SPECIES_PIDGEOTTO 17
#define SPECIES_PIDGEOT 18
#define SPECIES_RATTATA 19
#define SPECIES_RATICATE 20
#define SPECIES_SPEAROW 21
#define SPECIES_FEAROW 22
#define SPECIES_EKANS 23
#define SPECIES_ARBOK 24
#define SPECIES_PIKACHU 25
#define SPECIES_RAICHU 26
#define SPECIES_SANDSHREW 27
#define SPECIES_SANDSLASH 28
#define SPECIES_NIDORAN_F 29
#define SPECIES_NIDORINA 30
#define SPECIES_NIDOQUEEN 31
#define SPECIES_NIDORAN_M 32
#define SPECIES_NIDORINO 33
#define SPECIES_NIDOKING 34
#define SPECIES_CLEFAIRY 35
#define SPECIES_CLEFABLE 36
#define SPECIES_VULPIX 37
#define SPECIES_NINETALES 38
#define SPECIES_JIGGLYPUFF 39
#define SPECIES_WIGGLYTUFF 40
#define SPECIES_ZUBAT 41
#define SPECIES_GOLBAT 42
#define SPECIES_ODDISH 43
#define SPECIES_GLOOM 44
#define SPECIES_VILEPLUME 45
#define SPECIES_PARAS 46
#define SPECIES_PARASECT 47
#define SPECIES_VENONAT 48
#define SPECIES_VENOMOTH 49
#define SPECIES_DIGLETT 50
#define SPECIES_DUGTRIO 51
#define SPECIES_MEOWTH 52
#define SPECIES_PERSIAN 53
#define SPECIES_PSYDUCK 54
#define SPECIES_GOLDUCK 55
#define SPECIES_MANKEY 56
#define SPECIES_PRIMEAPE 57
#define SPECIES_GROWLITHE 58
#define SPECIES_ARCANINE 59
#define SPECIES_POLIWAG 60
#define SPECIES_POLIWHIRL 61
#define SPECIES_POLIWRATH 62
#define SPECIES_ABRA 63
#define SPECIES_KADABRA 64
#define SPECIES_ALAKAZAM 65
#define SPECIES_MACHOP 66
#define SPECIES_MACHOKE 67
#define SPECIES_MACHAMP 68
#define SPECIES_BELLSPROUT 69
#define SPECIES_WEEPINBELL 70
#define SPECIES_VICTREEBEL 71
#define SPECIES_TENTACOOL 72
#define SPECIES_TENTACRUEL 73
#define SPECIES_GEODUDE 74
#define SPECIES_GRAVELER 75
#define SPECIES_GOLEM 76
#define SPECIES_PONYTA 77
#define SPECIES_RAPIDASH 78
#define SPECIES_SLOWPOKE 79
#define SPECIES_SLOWBRO 80
#define SPECIES_MAGNEMITE 81
#define SPECIES_MAGNETON 82
#define SPECIES_FARFETCHD 83
#define SPECIES_DODUO 84
#define SPECIES_DODRIO 85
#define SPECIES_SEEL 86
#define SPECIES_DEWGONG 87
#define SPECIES_GRIMER 88
#define SPECIES_MUK 89
#define SPECIES_SHELLDER 90
#define SPECIES_CLOYSTER 91
#define SPECIES_GASTLY 92
#define SPECIES_HAUNTER 93
#define SPECIES_GENGAR 94
#define SPECIES_ONIX 95
#define SPECIES_DROWZEE 96
#define SPECIES_HYPNO 97
#define SPECIES_KRABBY 98
#define SPECIES_KINGLER 99
#define SPECIES_VOLTORB 100
#define SPECIES_ELECTRODE 101
#define SPECIES_EXEGGCUTE 102
#define SPECIES_EXEGGUTOR 103
#define SPECIES_CUBONE 104
#define SPECIES_MAROWAK 105
#define SPECIES_HITMONLEE 106
#define SPECIES_HITMONCHAN 107
#define SPECIES_LICKITUNG 108
#define SPECIES_KOFFING 109
#define SPECIES_WEEZING 110
#define SPECIES_RHYHORN 111
#define SPECIES_RHYDON 112
#define SPECIES_CHANSEY 113
#define SPECIES_TANGELA 114
#define SPECIES_KANGASKHAN 115
#define SPECIES_HORSEA 116
#define SPECIES_SEADRA 117
#define SPECIES_GOLDEEN 118
#define SPECIES_SEAKING 119
#define SPECIES_STARYU 120
#define SPECIES_STARMIE 121
#define SPECIES_MR_MIME 122
#define SPECIES_SCYTHER 123
#define SPECIES_JYNX 124
#define SPECIES_ELECTABUZZ 125
#define SPECIES_MAGMAR 126
#define SPECIES_PINSIR 127
#define SPECIES_TAUROS 128
#define SPECIES_MAGIKARP 129
#define SPECIES_GYARADOS 130
#define SPECIES_LAPRAS 131
#define SPECIES_DITTO 132
#define SPECIES_EEVEE 133
#define SPECIES_VAPOREON 134
#define SPECIES_JOLTEON 135
#define SPECIES_FLAREON 136
#define SPECIES_PORYGON 137
#define SPECIES_OMANYTE 138
#define SPECIES_OMASTAR 139
#define SPECIES_KABUTO 140
#define SPECIES_KABUTOPS 141
#define SPECIES_AERODACTYL 142
#define SPECIES_SNORLAX 143
#define SPECIES_ARTICUNO 144
#define SPECIES_ZAPDOS 145
#define SPECIES_MOLTRES 146
#define SPECIES_DRATINI 147
#define SPECIES_DRAGONAIR 148
#define SPECIES_DRAGONITE 149
#define SPECIES_MEWTWO 150
#define SPECIES_MEW 151
#define SPECIES_CHIKORITA 152
#define SPECIES_BAYLEEF 153
#define SPECIES_MEGANIUM 154
#define SPECIES_CYNDAQUIL 155
#define SPECIES_QUILAVA 156
#define SPECIES_TYPHLOSION 157
#define SPECIES_TOTODILE 158
#define SPECIES_CROCONAW 159
#define SPECIES_FERALIGATR 160
#define SPECIES_SENTRET 161
#define SPECIES_FURRET 162
#define SPECIES_HOOTHOOT 163
#define SPECIES_NOCTOWL 164
#define SPECIES_LEDYBA 165
#define SPECIES_LEDIAN 166
#define SPECIES_SPINARAK 167
#define SPECIES_ARIADOS 168
#define SPECIES_CROBAT 169
#define SPECIES_CHINCHOU 170
#define SPECIES_LANTURN 171
#define SPECIES_PICHU 172
#define SPECIES_CLEFFA 173
#define SPECIES_IGGLYBUFF 174
#define SPECIES_TOGEPI 175
#define SPECIES_TOGETIC 176
#define SPECIES_NATU 177
#define SPECIES_XATU 178
#define SPECIES_MAREEP 179
#define SPECIES_FLAAFFY 180
#define SPECIES_AMPHAROS 181
#define SPECIES_BELLOSSOM 182
#define SPECIES_MARILL 183
#define SPECIES_AZUMARILL 184
#define SPECIES_SUDOWOODO 185
#define SPECIES_POLITOED 186
#define SPECIES_HOPPIP 187
#define SPECIES_SKIPLOOM 188
#define SPECIES_JUMPLUFF 189
#define SPECIES_AIPOM 190
#define SPECIES_SUNKERN 191
#define SPECIES_SUNFLORA 192
#define SPECIES_YANMA 193
#define SPECIES_WOOPER 194
#define SPECIES_QUAGSIRE 195
#define SPECIES_ESPEON 196
#define SPECIES_UMBREON 197
#define SPECIES_MURKROW 198
#define SPECIES_SLOWKING 199
#define SPECIES_MISDREAVUS 200
#define SPECIES_UNOWN 201
#define SPECIES_WOBBUFFET 202
#define SPECIES_GIRAFARIG 203
#define SPECIES_PINECO 204
#define SPECIES_FORRETRESS 205
#define SPECIES_DUNSPARCE 206
#define SPECIES_GLIGAR 207
#define SPECIES_STEELIX 208
#define SPECIES_SNUBBULL 209
#define SPECIES_GRANBULL 210
#define SPECIES_QWILFISH 211
#define SPECIES_SCIZOR 212
#define SPECIES_SHUCKLE 213
#define SPECIES_HERACROSS 214
#define SPECIES_SNEASEL 215
#define SPECIES_TEDDIURSA 216
#define SPECIES_URSARING 217
#define SPECIES_SLUGMA 218
#define SPECIES_MAGCARGO 219
#define SPECIES_SWINUB 220
#define SPECIES_PILOSWINE 221
#define SPECIES_CORSOLA 222
#define SPECIES_REMORAID 223
#define SPECIES_OCTILLERY 224
#define SPECIES_DELIBIRD 225
#define SPECIES_MANTINE 226
#define SPECIES_SKARMORY 227
#define SPECIES_HOUNDOUR 228
#define SPECIES_HOUNDOOM 229
#define SPECIES_KINGDRA 230
#define SPECIES_PHANPY 231
#define SPECIES_DONPHAN 232
#define SPECIES_PORYGON2 233
#define SPECIES_STANTLER 234
#define SPECIES_SMEARGLE 235
#define SPECIES_TYROGUE 236
#define SPECIES_HITMONTOP 237
#define SPECIES_SMOOCHUM 238
#define SPECIES_ELEKID 239
#define SPECIES_MAGBY 240
#define SPECIES_MILTANK 241
#define SPECIES_BLISSEY 242
#define SPECIES_RAIKOU 243
#define SPECIES_ENTEI 244
#define SPECIES_SUICUNE 245
#define SPECIES_LARVITAR 246
#define SPECIES_PUPITAR 247
#define SPECIES_TYRANITAR 248
#define SPECIES_LUGIA 249
#define SPECIES_HO_OH 250
#define SPECIES_CELEBI 251
#define SPECIES_TREECKO 252
#define SPECIES_GROVYLE 253
#define SPECIES_SCEPTILE 254
#define SPECIES_TORCHIC 255
#define SPECIES_COMBUSKEN 256
#define SPECIES_BLAZIKEN 257
#define SPECIES_MUDKIP 258
#define SPECIES_MARSHTOMP 259
#define SPECIES_SWAMPERT 260
#define SPECIES_POOCHYENA 261
#define SPECIES_MIGHTYENA 262
#define SPECIES_ZIGZAGOON 263
#define SPECIES_LINOONE 264
#define SPECIES_WURMPLE 265
#define SPECIES_SILCOON 266
#define SPECIES_BEAUTIFLY 267
#define SPECIES_CASCOON 268
#define SPECIES_DUSTOX 269
#define SPECIES_LOTAD 270
#define SPECIES_LOMBRE 271
#define SPECIES_LUDICOLO 272
#define SPECIES_SEEDOT 273
#define SPECIES_NUZLEAF 274
#define SPECIES_SHIFTRY 275
#define SPECIES_TAILLOW 276
#define SPECIES_SWELLOW 277
#define SPECIES_WINGULL 278
#define SPECIES_PELIPPER 279
#define SPECIES_RALTS 280
#define SPECIES_KIRLIA 281
#define SPECIES_GARDEVOIR 282
#define SPECIES_SURSKIT 283
#define SPECIES_MASQUERAIN 284
#define SPECIES_SHROOMISH 285
#define SPECIES_BRELOOM 286
#define SPECIES_SLAKOTH 287
#define SPECIES_VIGOROTH 288
#define SPECIES_SLAKING 289
#define SPECIES_NINCADA 290
#define SPECIES_NINJASK 291
#define SPECIES_SHEDINJA 292
#define SPECIES_WHISMUR 293
#define SPECIES_LOUDRED 294
#define SPECIES_EXPLOUD 295
#define SPECIES_MAKUHITA 296
#define SPECIES_HARIYAMA 297
#define SPECIES_AZURILL 298
#define SPECIES_NOSEPASS 299
#define SPECIES_SKITTY 300
#define SPECIES_DELCATTY 301
#define SPECIES_SABLEYE 302
#define SPECIES_MAWILE 303
#define SPECIES_ARON 304
#define SPECIES_LAIRON 305
#define SPECIES_AGGRON 306
#define SPECIES_MEDITITE 307
#define SPECIES_MEDICHAM 308
#define SPECIES_ELECTRIKE 309
#define SPECIES_MANECTRIC 310
#define SPECIES_PLUSLE 311
#define SPECIES_MINUN 312
#define SPECIES_VOLBEAT 313
#define SPECIES_ILLUMISE 314
#define SPECIES_ROSELIA 315
#define SPECIES_GULPIN 316
#define SPECIES_SWALOT 317
#define SPECIES_CARVANHA 318
#define SPECIES_SHARPEDO 319
#define SPECIES_WAILMER 320
#define SPECIES_WAILORD 321
#define SPECIES_NUMEL 322
#define SPECIES_CAMERUPT 323
#define SPECIES_TORKOAL 324
#define SPECIES_SPOINK 325
#define SPECIES_GRUMPIG 326
#define SPECIES_SPINDA 327
#define SPECIES_TRAPINCH 328
#define SPECIES_VIBRAVA 329
#define SPECIES_FLYGON 330
#define SPECIES_CACNEA 331
#define SPECIES_CACTURNE 332
#define SPECIES_SWABLU 333
#define SPECIES_ALTARIA 334
#define SPECIES_ZANGOOSE 335
#define SPECIES_SEVIPER 336
#define SPECIES_LUNATONE 337
#define SPECIES_SOLROCK 338
#define SPECIES_BARBOACH 339
#define SPECIES_WHISCASH 340
#define SPECIES_CORPHISH 341
#define SPECIES_CRAWDAUNT 342
#define SPECIES_BALTOY 343
#define SPECIES_CLAYDOL 344
#define SPECIES_LILEEP 345
#define SPECIES_CRADILY 346
#define SPECIES_ANORITH 347
#define SPECIES_ARMALDO 348
#define SPECIES_FEEBAS 349
#define SPECIES_MILOTIC 350
#define SPECIES_CASTFORM 351
#define SPECIES_KECLEON 352
#define SPECIES_SHUPPET 353
#define SPECIES_BANETTE 354
#define SPECIES_DUSKULL 355
#define SPECIES_DUSCLOPS 356
#define SPECIES_TROPIUS 357
#define SPECIES_CHIMECHO 358
#define SPECIES_ABSOL 359
#define SPECIES_WYNAUT 360
#define SPECIES_SNORUNT 361
#define SPECIES_GLALIE 362
#define SPECIES_SPHEAL 363
#define SPECIES_SEALEO 364
#define SPECIES_WALREIN 365
#define SPECIES_CLAMPERL 366
#define SPECIES_HUNTAIL 367
#define SPECIES_GOREBYSS 368
#define SPECIES_RELICANTH 369
#define SPECIES_LUVDISC 370
#define SPECIES_BAGON 371
#define SPECIES_SHELGON 372
#define SPECIES_SALAMENCE 373
#define SPECIES_BELDUM 374
#define SPECIES_METANG 375
#define SPECIES_METAGROSS 376
#define SPECIES_REGIROCK 377
#define SPECIES_REGICE 378
#define SPECIES_REGISTEEL 379
#define SPECIES_LATIAS 380
#define SPECIES_LATIOS 381
#define SPECIES_KYOGRE 382
#define SPECIES_GROUDON 383
#define SPECIES_RAYQUAZA 384
#define SPECIES_JIRACHI 385
#define SPECIES_DEOXYS 386

#define SPECIES_BUDEW 387
#define SPECIES_ROSERADE 388
#define SPECIES_AMBIPOM 389
#define SPECIES_MISMAGIUS 390
#define SPECIES_HONCHKROW 391
#define SPECIES_CHINGLING 392
#define SPECIES_BONSLY 393
#define SPECIES_MIME_JR 394
#define SPECIES_HAPPINY 395
#define SPECIES_MUNCHLAX 396
#define SPECIES_RIOLU 397
#define SPECIES_LUCARIO 398
#define SPECIES_MANTYKE 399
#define SPECIES_WEAVILE 400
#define SPECIES_MAGNEZONE 401
#define SPECIES_PORYGON_Z 402
#define SPECIES_LICKILICKY 403
#define SPECIES_RHYPERIOR 404
#define SPECIES_TANGROWTH 405
#define SPECIES_ELECTIVIRE 406
#define SPECIES_MAGMORTAR 407
#define SPECIES_TOGEKISS 408
#define SPECIES_YANMEGA 409
#define SPECIES_LEAFEON 410
#define SPECIES_GLACEON 411
#define SPECIES_GLISCOR 412
#define SPECIES_MAMOSWINE 413
#define SPECIES_GALLADE 414
#define SPECIES_PROBOPASS 415
#define SPECIES_DUSKNOIR 416
#define SPECIES_FROSLASS 417
#define SPECIES_REGIGIGAS 418

#define SPECIES_SYLVEON 419

#define SPECIES_RATTATA_ALOLAN 422
#define SPECIES_RATICATE_ALOLAN 423
#define SPECIES_RAICHU_ALOLAN 424
#define SPECIES_SANDSHREW_ALOLAN 425
#define SPECIES_SANDSLASH_ALOLAN 426
#define SPECIES_VULPIX_ALOLAN 427
#define SPECIES_NINETALES_ALOLAN 428 
#define SPECIES_DIGLETT_ALOLAN 429
#define SPECIES_DUGTRIO_ALOLAN 430
#define SPECIES_MEOWTH_ALOLAN 431
#define SPECIES_PERSIAN_ALOLAN 432 
#define SPECIES_GEODUDE_ALOLAN 433
#define SPECIES_GRAVELER_ALOLAN 434 
#define SPECIES_GOLEM_ALOLAN 435
#define SPECIES_GRIMER_ALOLAN 436
#define SPECIES_MUK_ALOLAN 437
#define SPECIES_EXEGGUTOR_ALOLAN 438
#define SPECIES_MAROWAK_ALOLAN 439

#define SPECIES_PONYTA_GALARIAN 440
#define SPECIES_RAPIDASH_GALARIAN 441
#define SPECIES_SLOWPOKE_GALARIAN 442
#define SPECIES_SLOWBRO_GALARIAN 443
#define SPECIES_SLOWKING_GALARIAN 444
#define SPECIES_WEEZING_GALARIAN 445
#define SPECIES_ZIGZAGOON_GALARIAN 446
#define SPECIES_LINOONE_GALARIAN 447
#define SPECIES_OBSTAGOON 448
#define SPECIES_MEOWTH_GALARIAN 449
#define SPECIES_PERRSERKER 450
#define SPECIES_CORSOLA_GALARIAN 451
#define SPECIES_CURSOLA 452
#define SPECIES_FARFETCHD_GALARIAN 453
#define SPECIES_SIRFETCHD 454
#define SPECIES_MR_MIME_GALARIAN 455
#define SPECIES_MR_RIME 456

#define SPECIES_ARTICUNO_GALARIAN 457
#define SPECIES_ZAPDOS_GALARIAN 458
#define SPECIES_MOLTRES_GALARIAN 459
#define SPECIES_REGIELEKI 460
#define SPECIES_REGIDRAGO 461

#define SPECIES_WYRDEER 500
#define SPECIES_KLEAVOR 501
#define SPECIES_URSALUNA 502
#define SPECIES_SNEASLER 503
#define SPECIES_OVERQWIL 504

// Megas
#define SPECIES_VENUSAUR_MEGA                FORMS_START + 1
#define SPECIES_CHARIZARD_MEGA_X             FORMS_START + 2
#define SPECIES_CHARIZARD_MEGA_Y             FORMS_START + 3
#define SPECIES_BLASTOISE_MEGA               FORMS_START + 4
#define SPECIES_BEEDRILL_MEGA                FORMS_START + 5
#define SPECIES_PIDGEOT_MEGA                 FORMS_START + 6
#define SPECIES_ALAKAZAM_MEGA                FORMS_START + 7
#define SPECIES_SLOWBRO_MEGA                 FORMS_START + 8
#define SPECIES_GENGAR_MEGA                  FORMS_START + 9
#define SPECIES_KANGASKHAN_MEGA              FORMS_START + 10
#define SPECIES_PINSIR_MEGA                  FORMS_START + 11
#define SPECIES_GYARADOS_MEGA                FORMS_START + 12
#define SPECIES_AERODACTYL_MEGA              FORMS_START + 13
#define SPECIES_MEWTWO_MEGA_X                FORMS_START + 14
#define SPECIES_MEWTWO_MEGA_Y                FORMS_START + 15
#define SPECIES_AMPHAROS_MEGA                FORMS_START + 16
#define SPECIES_STEELIX_MEGA                 FORMS_START + 17
#define SPECIES_SCIZOR_MEGA                  FORMS_START + 18
#define SPECIES_HERACROSS_MEGA               FORMS_START + 19
#define SPECIES_HOUNDOOM_MEGA                FORMS_START + 20
#define SPECIES_TYRANITAR_MEGA               FORMS_START + 21
#define SPECIES_SCEPTILE_MEGA                FORMS_START + 22
#define SPECIES_BLAZIKEN_MEGA                FORMS_START + 23
#define SPECIES_SWAMPERT_MEGA                FORMS_START + 24
#define SPECIES_GARDEVOIR_MEGA               FORMS_START + 25
#define SPECIES_SABLEYE_MEGA                 FORMS_START + 26
#define SPECIES_MAWILE_MEGA                  FORMS_START + 27
#define SPECIES_AGGRON_MEGA                  FORMS_START + 28
#define SPECIES_MEDICHAM_MEGA                FORMS_START + 29
#define SPECIES_MANECTRIC_MEGA               FORMS_START + 30
#define SPECIES_SHARPEDO_MEGA                FORMS_START + 31
#define SPECIES_CAMERUPT_MEGA                FORMS_START + 32
#define SPECIES_ALTARIA_MEGA                 FORMS_START + 33
#define SPECIES_BANETTE_MEGA                 FORMS_START + 34
#define SPECIES_ABSOL_MEGA                   FORMS_START + 35
#define SPECIES_GLALIE_MEGA                  FORMS_START + 36
#define SPECIES_SALAMENCE_MEGA               FORMS_START + 37
#define SPECIES_METAGROSS_MEGA               FORMS_START + 38
#define SPECIES_LATIAS_MEGA                  FORMS_START + 39
#define SPECIES_LATIOS_MEGA                  FORMS_START + 40
#define SPECIES_LOPUNNY_MEGA                 FORMS_START + 41
#define SPECIES_GARCHOMP_MEGA                FORMS_START + 42
#define SPECIES_LUCARIO_MEGA                 FORMS_START + 43
#define SPECIES_ABOMASNOW_MEGA               FORMS_START + 44
#define SPECIES_GALLADE_MEGA                 FORMS_START + 45
#define SPECIES_AUDINO_MEGA                  FORMS_START + 46
#define SPECIES_DIANCIE_MEGA                 FORMS_START + 47

// Special Mega + Primals
#define SPECIES_RAYQUAZA_MEGA                FORMS_START + 48
#define SPECIES_KYOGRE_PRIMAL                FORMS_START + 49
#define SPECIES_GROUDON_PRIMAL               FORMS_START + 50

// Alolan Forms

// Galarian Forms

//Hisuian Forms
#define SPECIES_GROWLITHE_HISUIAN            FORMS_START + 88
#define SPECIES_ARCANINE_HISUIAN             FORMS_START + 89
#define SPECIES_VOLTORB_HISUIAN              FORMS_START + 90
#define SPECIES_ELECTRODE_HISUIAN            FORMS_START + 91
#define SPECIES_TYPHLOSION_HISUIAN           FORMS_START + 92
#define SPECIES_QWILFISH_HISUIAN             FORMS_START + 93
#define SPECIES_SNEASEL_HISUIAN              FORMS_START + 94
#define SPECIES_SAMUROTT_HISUIAN             FORMS_START + 95
#define SPECIES_LILLIGANT_HISUIAN            FORMS_START + 96
#define SPECIES_ZORUA_HISUIAN                FORMS_START + 97
#define SPECIES_ZOROARK_HISUIAN              FORMS_START + 98
#define SPECIES_BRAVIARY_HISUIAN             FORMS_START + 99
#define SPECIES_SLIGGOO_HISUIAN              FORMS_START + 100
#define SPECIES_GOODRA_HISUIAN               FORMS_START + 101
#define SPECIES_AVALUGG_HISUIAN              FORMS_START + 102
#define SPECIES_DECIDUEYE_HISUIAN            FORMS_START + 103

//UNUSED MONS

#define SPECIES_TURTWIG 600
#define SPECIES_GROTLE  601
#define SPECIES_TORTERRA 602
#define SPECIES_CHIMCHAR 603
#define SPECIES_MONFERNO 604
#define SPECIES_INFERNAPE 605
#define SPECIES_PIPLUP 606
#define SPECIES_PRINPLUP 607
#define SPECIES_EMPOLEON 608
#define SPECIES_STARLY 609
#define SPECIES_STARAVIA 610
#define SPECIES_STARAPTOR 611
#define SPECIES_BIDOOF 612
#define SPECIES_BIBAREL 613
#define SPECIES_KRICKETOT 614
#define SPECIES_KRICKETUNE 615
#define SPECIES_SHINX 616
#define SPECIES_LUXIO 617
#define SPECIES_LUXRAY 618
#define SPECIES_CRANIDOS 619
#define SPECIES_RAMPARDOS 620
#define SPECIES_SHIELDON 621
#define SPECIES_BASTIODON 622
#define SPECIES_BURMY 623
#define SPECIES_WORMADAM 624
#define SPECIES_MOTHIM 625
#define SPECIES_COMBEE 626
#define SPECIES_VESPIQUEN 627
#define SPECIES_PACHIRISU 628
#define SPECIES_BUIZEL 629
#define SPECIES_FLOATZEL 630
#define SPECIES_CHERUBI 631
#define SPECIES_CHERRIM 632
#define SPECIES_SHELLOS 633
#define SPECIES_GASTRODON 634
#define SPECIES_DRIFLOON 635
#define SPECIES_DRIFBLIM 636
#define SPECIES_BUNEARY 637
#define SPECIES_LOPUNNY 638
#define SPECIES_GLAMEOW 639
#define SPECIES_PURUGLY 640
#define SPECIES_STUNKY 641
#define SPECIES_SKUNTANK 642
#define SPECIES_BRONZOR 643
#define SPECIES_BRONZONG 644
#define SPECIES_CHATOT 645
#define SPECIES_SPIRITOMB 646
#define SPECIES_GIBLE 647
#define SPECIES_GABITE 648
#define SPECIES_GARCHOMP 649
#define SPECIES_HIPPOPOTAS 650
#define SPECIES_HIPPOWDON 651
#define SPECIES_SKORUPI 652
#define SPECIES_DRAPION 653
#define SPECIES_CROAGUNK 654
#define SPECIES_TOXICROAK 655
#define SPECIES_CARNIVINE 656
#define SPECIES_FINNEON 657
#define SPECIES_LUMINEON 658
#define SPECIES_SNOVER 659
#define SPECIES_ABOMASNOW 660
#define SPECIES_ROTOM 661
#define SPECIES_UXIE 662
#define SPECIES_MESPRIT 663
#define SPECIES_AZELF 664
#define SPECIES_DIALGA 665
#define SPECIES_PALKIA 666
#define SPECIES_HEATRAN 667
#define SPECIES_GIRATINA 668
#define SPECIES_CRESSELIA 669
#define SPECIES_PHIONE 670
#define SPECIES_MANAPHY 671
#define SPECIES_DARKRAI 672
#define SPECIES_SHAYMIN 673
#define SPECIES_ARCEUS 674

#define SPECIES_VICTINI 675
#define SPECIES_SNIVY 676
#define SPECIES_SERVINE 677
#define SPECIES_SERPERIOR 678
#define SPECIES_TEPIG 679
#define SPECIES_PIGNITE 680
#define SPECIES_EMBOAR 681
#define SPECIES_OSHAWOTT 682
#define SPECIES_DEWOTT 683
#define SPECIES_SAMUROTT 684
#define SPECIES_PATRAT 685
#define SPECIES_WATCHOG 686
#define SPECIES_LILLIPUP 687
#define SPECIES_HERDIER 688
#define SPECIES_STOUTLAND 689
#define SPECIES_PURRLOIN 690
#define SPECIES_LIEPARD 691
#define SPECIES_PANSAGE 692
#define SPECIES_SIMISAGE 693
#define SPECIES_PANSEAR 694
#define SPECIES_SIMISEAR 695
#define SPECIES_PANPOUR 696
#define SPECIES_SIMIPOUR 697
#define SPECIES_MUNNA 698
#define SPECIES_MUSHARNA 699
#define SPECIES_PIDOVE 700
#define SPECIES_TRANQUILL 701
#define SPECIES_UNFEZANT 702
#define SPECIES_BLITZLE 703
#define SPECIES_ZEBSTRIKA 704
#define SPECIES_ROGGENROLA 705
#define SPECIES_BOLDORE 706
#define SPECIES_GIGALITH 707
#define SPECIES_WOOBAT 708
#define SPECIES_SWOOBAT 709
#define SPECIES_DRILBUR 710
#define SPECIES_EXCADRILL 711
#define SPECIES_AUDINO 712
#define SPECIES_TIMBURR 713
#define SPECIES_GURDURR 714
#define SPECIES_CONKELDURR 715
#define SPECIES_TYMPOLE 716
#define SPECIES_PALPITOAD 717
#define SPECIES_SEISMITOAD 718 
#define SPECIES_THROH 719
#define SPECIES_SAWK 720
#define SPECIES_SEWADDLE 721 
#define SPECIES_SWADLOON 722
#define SPECIES_LEAVANNY 723
#define SPECIES_VENIPEDE 724
#define SPECIES_WHIRLIPEDE 725
#define SPECIES_SCOLIPEDE 726
#define SPECIES_COTTONEE 727
#define SPECIES_WHIMSICOTT 728
#define SPECIES_PETILIL 729
#define SPECIES_LILLIGANT 730
#define SPECIES_BASCULIN 731
#define SPECIES_SANDILE 732
#define SPECIES_KROKOROK 733
#define SPECIES_KROOKODILE 734
#define SPECIES_DARUMAKA 735
#define SPECIES_DARMANITAN 736
#define SPECIES_MARACTUS 737
#define SPECIES_DWEBBLE 738
#define SPECIES_CRUSTLE 739
#define SPECIES_SCRAGGY 740
#define SPECIES_SCRAFTY 741
#define SPECIES_SIGILYPH 742
#define SPECIES_YAMASK 743
#define SPECIES_COFAGRIGUS 744 
#define SPECIES_TIRTOUGA 745
#define SPECIES_CARRACOSTA 746
#define SPECIES_ARCHEN 747
#define SPECIES_ARCHEOPS 748
#define SPECIES_TRUBBISH 749
#define SPECIES_GARBODOR 750
#define SPECIES_ZORUA 751
#define SPECIES_ZOROARK 752
#define SPECIES_MINCCINO 753
#define SPECIES_CINCCINO 754
#define SPECIES_GOTHITA 755
#define SPECIES_GOTHORITA 756
#define SPECIES_GOTHITELLE 757
#define SPECIES_SOLOSIS 758
#define SPECIES_DUOSION 759
#define SPECIES_REUNICLUS 760
#define SPECIES_DUCKLETT 761
#define SPECIES_SWANNA 762
#define SPECIES_VANILLITE 763
#define SPECIES_VANILLISH 764
#define SPECIES_VANILLUXE 765
#define SPECIES_DEERLING 766
#define SPECIES_SAWSBUCK 767
#define SPECIES_EMOLGA 768
#define SPECIES_KARRABLAST 769 
#define SPECIES_ESCAVALIER 770
#define SPECIES_FOONGUS 771
#define SPECIES_AMOONGUSS 772
#define SPECIES_FRILLISH 773
#define SPECIES_JELLICENT 774
#define SPECIES_ALOMOMOLA 775
#define SPECIES_JOLTIK 776
#define SPECIES_GALVANTULA 777 
#define SPECIES_FERROSEED 778
#define SPECIES_FERROTHORN 779
#define SPECIES_KLINK 780
#define SPECIES_KLANG 781
#define SPECIES_KLINKLANG 782 
#define SPECIES_TYNAMO 783
#define SPECIES_EELEKTRIK 784
#define SPECIES_EELEKTROSS 785
#define SPECIES_ELGYEM 786
#define SPECIES_BEHEEYEM 787
#define SPECIES_LITWICK 788
#define SPECIES_LAMPENT 789
#define SPECIES_CHANDELURE 790
#define SPECIES_AXEW 791
#define SPECIES_FRAXURE 792
#define SPECIES_HAXORUS 793
#define SPECIES_CUBCHOO 794
#define SPECIES_BEARTIC 795
#define SPECIES_CRYOGONAL 796
#define SPECIES_SHELMET 797
#define SPECIES_ACCELGOR 798
#define SPECIES_STUNFISK 799
#define SPECIES_MIENFOO 800
#define SPECIES_MIENSHAO 801 
#define SPECIES_DRUDDIGON 802
#define SPECIES_GOLETT 803
#define SPECIES_GOLURK 804
#define SPECIES_PAWNIARD 805
#define SPECIES_BISHARP 806
#define SPECIES_BOUFFALANT 807
#define SPECIES_RUFFLET 808
#define SPECIES_BRAVIARY 809
#define SPECIES_VULLABY 810
#define SPECIES_MANDIBUZZ 811
#define SPECIES_HEATMOR 812
#define SPECIES_DURANT 813
#define SPECIES_DEINO 814
#define SPECIES_ZWEILOUS 815
#define SPECIES_HYDREIGON 816
#define SPECIES_LARVESTA 817
#define SPECIES_VOLCARONA 818
#define SPECIES_COBALION 819
#define SPECIES_TERRAKION 820
#define SPECIES_VIRIZION 821
#define SPECIES_TORNADUS 822
#define SPECIES_THUNDURUS 823
#define SPECIES_RESHIRAM 824
#define SPECIES_ZEKROM 825
#define SPECIES_LANDORUS 826
#define SPECIES_KYUREM 827
#define SPECIES_KELDEO 828
#define SPECIES_MELOETTA 829
#define SPECIES_GENESECT 830

#define SPECIES_CHESPIN 831
#define SPECIES_QUILLADIN 832
#define SPECIES_CHESNAUGHT 833
#define SPECIES_FENNEKIN 834
#define SPECIES_BRAIXEN 835
#define SPECIES_DELPHOX 836
#define SPECIES_FROAKIE 837
#define SPECIES_FROGADIER 838
#define SPECIES_GRENINJA 839
#define SPECIES_BUNNELBY 840
#define SPECIES_DIGGERSBY 841
#define SPECIES_FLETCHLING 842
#define SPECIES_FLETCHINDER 843
#define SPECIES_TALONFLAME 844
#define SPECIES_SCATTERBUG 845
#define SPECIES_SPEWPA 846
#define SPECIES_VIVILLON  847// Icy Snow Pattern
#define SPECIES_LITLEO 848
#define SPECIES_PYROAR 849
#define SPECIES_FLABEBE 850// Red Flower
#define SPECIES_FLOETTE 851
#define SPECIES_FLORGES 852
#define SPECIES_SKIDDO 853
#define SPECIES_GOGOAT 854
#define SPECIES_PANCHAM 855
#define SPECIES_PANGORO 856
#define SPECIES_FURFROU 857
#define SPECIES_ESPURR 858
#define SPECIES_MEOWSTIC 859
#define SPECIES_HONEDGE 860
#define SPECIES_DOUBLADE 861
#define SPECIES_AEGISLASH 862
#define SPECIES_SPRITZEE 863
#define SPECIES_AROMATISSE 864
#define SPECIES_SWIRLIX 865
#define SPECIES_SLURPUFF 866
#define SPECIES_INKAY 867
#define SPECIES_MALAMAR 868
#define SPECIES_BINACLE 869
#define SPECIES_BARBARACLE 870
#define SPECIES_SKRELP 871
#define SPECIES_DRAGALGE 872
#define SPECIES_CLAUNCHER 873
#define SPECIES_CLAWITZER 874
#define SPECIES_HELIOPTILE 875
#define SPECIES_HELIOLISK 876
#define SPECIES_TYRUNT 877
#define SPECIES_TYRANTRUM 878
#define SPECIES_AMAURA 879
#define SPECIES_AURORUS 880
#define SPECIES_HAWLUCHA 881
#define SPECIES_DEDENNE 882
#define SPECIES_CARBINK 883
#define SPECIES_GOOMY 884
#define SPECIES_SLIGGOO 885
#define SPECIES_GOODRA 886
#define SPECIES_KLEFKI 887
#define SPECIES_PHANTUMP 888
#define SPECIES_TREVENANT 889
#define SPECIES_PUMPKABOO 890
#define SPECIES_GOURGEIST 891
#define SPECIES_BERGMITE 892
#define SPECIES_AVALUGG 893
#define SPECIES_NOIBAT 894
#define SPECIES_NOIVERN 895
#define SPECIES_XERNEAS 896
#define SPECIES_YVELTAL 897
#define SPECIES_ZYGARDE 898
#define SPECIES_DIANCIE 899
#define SPECIES_HOOPA 900
#define SPECIES_VOLCANION 901 

#define SPECIES_ROWLET 902
#define SPECIES_DARTRIX 903
#define SPECIES_DECIDUEYE 904
#define SPECIES_LITTEN 905
#define SPECIES_TORRACAT 906
#define SPECIES_INCINEROAR 907
#define SPECIES_POPPLIO 908
#define SPECIES_BRIONNE 909
#define SPECIES_PRIMARINA 910
#define SPECIES_PIKIPEK 911
#define SPECIES_TRUMBEAK 912
#define SPECIES_TOUCANNON 913
#define SPECIES_YUNGOOS 914
#define SPECIES_GUMSHOOS 915
#define SPECIES_GRUBBIN 916
#define SPECIES_CHARJABUG 917
#define SPECIES_VIKAVOLT 918
#define SPECIES_CRABRAWLER 919
#define SPECIES_CRABOMINABLE 920
#define SPECIES_ORICORIO 921
#define SPECIES_CUTIEFLY 922
#define SPECIES_RIBOMBEE 923
#define SPECIES_ROCKRUFF 924
#define SPECIES_LYCANROC 925
#define SPECIES_WISHIWASHI 926
#define SPECIES_MAREANIE 927
#define SPECIES_TOXAPEX 928
#define SPECIES_MUDBRAY 929
#define SPECIES_MUDSDALE 930
#define SPECIES_DEWPIDER 931
#define SPECIES_ARAQUANID 932
#define SPECIES_FOMANTIS 933
#define SPECIES_LURANTIS 934
#define SPECIES_MORELULL 935
#define SPECIES_SHIINOTIC 936
#define SPECIES_SALANDIT 937
#define SPECIES_SALAZZLE 938
#define SPECIES_STUFFUL 939
#define SPECIES_BEWEAR 940
#define SPECIES_BOUNSWEET 941 
#define SPECIES_STEENEE 942
#define SPECIES_TSAREENA 943
#define SPECIES_COMFEY 944
#define SPECIES_ORANGURU 945
#define SPECIES_PASSIMIAN 946
#define SPECIES_WIMPOD 947
#define SPECIES_GOLISOPOD 948
#define SPECIES_SANDYGAST 949
#define SPECIES_PALOSSAND 950
#define SPECIES_PYUKUMUKU 951
#define SPECIES_TYPE_NULL 952
#define SPECIES_SILVALLY 953
#define SPECIES_MINIOR 954
#define SPECIES_KOMALA 955
#define SPECIES_TURTONATOR 956 
#define SPECIES_TOGEDEMARU 957
#define SPECIES_MIMIKYU 958
#define SPECIES_BRUXISH 959
#define SPECIES_DRAMPA 960
#define SPECIES_DHELMISE 961
#define SPECIES_JANGMO_O 962
#define SPECIES_HAKAMO_O 963
#define SPECIES_KOMMO_O 964
#define SPECIES_TAPU_KOKO 965
#define SPECIES_TAPU_LELE 966
#define SPECIES_TAPU_BULU 967
#define SPECIES_TAPU_FINI 968
#define SPECIES_COSMOG 969
#define SPECIES_COSMOEM 970
#define SPECIES_SOLGALEO 971
#define SPECIES_LUNALA 972
#define SPECIES_NIHILEGO 973
#define SPECIES_BUZZWOLE 974
#define SPECIES_PHEROMOSA 975
#define SPECIES_XURKITREE 976
#define SPECIES_CELESTEELA 977
#define SPECIES_KARTANA 978
#define SPECIES_GUZZLORD 979
#define SPECIES_NECROZMA 980
#define SPECIES_MAGEARNA 981
#define SPECIES_MARSHADOW 982
#define SPECIES_POIPOLE 983
#define SPECIES_NAGANADEL 984
#define SPECIES_STAKATAKA 985
#define SPECIES_BLACEPHALON 986
#define SPECIES_ZERAORA 987
#define SPECIES_MELTAN 988
#define SPECIES_MELMETAL 989

#define SPECIES_GROOKEY 990
#define SPECIES_THWACKEY 991
#define SPECIES_RILLABOOM 992
#define SPECIES_SCORBUNNY 993
#define SPECIES_RABOOT 994
#define SPECIES_CINDERACE 995
#define SPECIES_SOBBLE 996
#define SPECIES_DRIZZILE 997
#define SPECIES_INTELEON 998
#define SPECIES_SKWOVET 999
#define SPECIES_GREEDENT 1000
#define SPECIES_ROOKIDEE 1001
#define SPECIES_CORVISQUIRE 1002
#define SPECIES_CORVIKNIGHT 1003
#define SPECIES_BLIPBUG 1004
#define SPECIES_DOTTLER 1005
#define SPECIES_ORBEETLE 1006
#define SPECIES_NICKIT 1007
#define SPECIES_THIEVUL 1008
#define SPECIES_GOSSIFLEUR 1009
#define SPECIES_ELDEGOSS 1010
#define SPECIES_WOOLOO 1011
#define SPECIES_DUBWOOL 1012
#define SPECIES_CHEWTLE 1013
#define SPECIES_DREDNAW 1014
#define SPECIES_YAMPER 1015
#define SPECIES_BOLTUND 1016
#define SPECIES_ROLYCOLY 1017
#define SPECIES_CARKOL 1018
#define SPECIES_COALOSSAL 1019
#define SPECIES_APPLIN 1020
#define SPECIES_FLAPPLE 1021
#define SPECIES_APPLETUN 1022
#define SPECIES_SILICOBRA 1023
#define SPECIES_SANDACONDA 1024
#define SPECIES_CRAMORANT 1025
#define SPECIES_ARROKUDA 1026
#define SPECIES_BARRASKEWDA 1027
#define SPECIES_TOXEL 1028
#define SPECIES_TOXTRICITY 1029
#define SPECIES_SIZZLIPEDE 1030
#define SPECIES_CENTISKORCH 1031
#define SPECIES_CLOBBOPUS 1032
#define SPECIES_GRAPPLOCT 1033
#define SPECIES_SINISTEA 1034
#define SPECIES_POLTEAGEIST 1035
#define SPECIES_HATENNA 1036
#define SPECIES_HATTREM 1037
#define SPECIES_HATTERENE 1038
#define SPECIES_IMPIDIMP 1039
#define SPECIES_MORGREM 1040
#define SPECIES_GRIMMSNARL 1041
#define SPECIES_RUNERIGUS 1042
#define SPECIES_MILCERY 1043
#define SPECIES_ALCREMIE 1044
#define SPECIES_FALINKS 1045
#define SPECIES_PINCURCHIN 1046
#define SPECIES_SNOM 1047
#define SPECIES_FROSMOTH 1048
#define SPECIES_STONJOURNER 1049
#define SPECIES_EISCUE 1050
#define SPECIES_INDEEDEE 1051
#define SPECIES_MORPEKO 1052
#define SPECIES_CUFANT 1053
#define SPECIES_COPPERAJAH 1054
#define SPECIES_DRACOZOLT 1055
#define SPECIES_ARCTOZOLT 1056
#define SPECIES_DRACOVISH 1057
#define SPECIES_ARCTOVISH 1058
#define SPECIES_DURALUDON 1059
#define SPECIES_DREEPY 1060
#define SPECIES_DRAKLOAK 1061
#define SPECIES_DRAGAPULT 1062
#define SPECIES_ZACIAN 1063
#define SPECIES_ZAMAZENTA 1064
#define SPECIES_ETERNATUS 1065
#define SPECIES_KUBFU 1066
#define SPECIES_URSHIFU 1067
#define SPECIES_ZARUDE 1068
#define SPECIES_GLASTRIER 1069
#define SPECIES_SPECTRIER 1070
#define SPECIES_CALYREX 1071

#define SPECIES_DARUMAKA_GALARIAN 1072
#define SPECIES_DARMANITAN_GALARIAN 1073
#define SPECIES_YAMASK_GALARIAN 1074
#define SPECIES_STUNFISK_GALARIAN 1075

#define SPECIES_BASCULEGION 1076
#define SPECIES_ENAMORUS 1077

// Misc Forms

// Cosplay Pikachu
#define SPECIES_PIKACHU_COSPLAY              FORMS_START + 104
#define SPECIES_PIKACHU_ROCK_STAR            FORMS_START + 105
#define SPECIES_PIKACHU_BELLE                FORMS_START + 106
#define SPECIES_PIKACHU_POP_STAR             FORMS_START + 107
#define SPECIES_PIKACHU_PH_D                 FORMS_START + 108
#define SPECIES_PIKACHU_LIBRE                FORMS_START + 109

// Cap Pikachu
#define SPECIES_PIKACHU_ORIGINAL_CAP         FORMS_START + 110
#define SPECIES_PIKACHU_HOENN_CAP            FORMS_START + 111
#define SPECIES_PIKACHU_SINNOH_CAP           FORMS_START + 112
#define SPECIES_PIKACHU_UNOVA_CAP            FORMS_START + 113
#define SPECIES_PIKACHU_KALOS_CAP            FORMS_START + 114
#define SPECIES_PIKACHU_ALOLA_CAP            FORMS_START + 115
#define SPECIES_PIKACHU_PARTNER_CAP          FORMS_START + 116
#define SPECIES_PIKACHU_WORLD_CAP            FORMS_START + 117

// Pichu
#define SPECIES_PICHU_SPIKY_EARED            FORMS_START + 118

// Unown
#define SPECIES_UNOWN_B                      FORMS_START + 119
#define SPECIES_UNOWN_C                      FORMS_START + 120
#define SPECIES_UNOWN_D                      FORMS_START + 121
#define SPECIES_UNOWN_E                      FORMS_START + 122
#define SPECIES_UNOWN_F                      FORMS_START + 123
#define SPECIES_UNOWN_G                      FORMS_START + 124
#define SPECIES_UNOWN_H                      FORMS_START + 125
#define SPECIES_UNOWN_I                      FORMS_START + 126
#define SPECIES_UNOWN_J                      FORMS_START + 127
#define SPECIES_UNOWN_K                      FORMS_START + 128
#define SPECIES_UNOWN_L                      FORMS_START + 129
#define SPECIES_UNOWN_M                      FORMS_START + 130
#define SPECIES_UNOWN_N                      FORMS_START + 131
#define SPECIES_UNOWN_O                      FORMS_START + 132
#define SPECIES_UNOWN_P                      FORMS_START + 133
#define SPECIES_UNOWN_Q                      FORMS_START + 134
#define SPECIES_UNOWN_R                      FORMS_START + 135
#define SPECIES_UNOWN_S                      FORMS_START + 136
#define SPECIES_UNOWN_T                      FORMS_START + 137
#define SPECIES_UNOWN_U                      FORMS_START + 138
#define SPECIES_UNOWN_V                      FORMS_START + 139
#define SPECIES_UNOWN_W                      FORMS_START + 140
#define SPECIES_UNOWN_X                      FORMS_START + 141
#define SPECIES_UNOWN_Y                      FORMS_START + 142
#define SPECIES_UNOWN_Z                      FORMS_START + 143
#define SPECIES_UNOWN_EMARK                  FORMS_START + 144
#define SPECIES_UNOWN_QMARK                  FORMS_START + 145

// Castform
#define SPECIES_CASTFORM_SUNNY               FORMS_START + 146
#define SPECIES_CASTFORM_RAINY               FORMS_START + 147
#define SPECIES_CASTFORM_SNOWY               FORMS_START + 148

// Deoxys
#define SPECIES_DEOXYS_ATTACK                FORMS_START + 149
#define SPECIES_DEOXYS_DEFENSE               FORMS_START + 150
#define SPECIES_DEOXYS_SPEED                 FORMS_START + 151



 // Burmy
#define SPECIES_BURMY_SANDY_CLOAK            FORMS_START + 152
#define SPECIES_BURMY_TRASH_CLOAK            FORMS_START + 153

// Wormadam
#define SPECIES_WORMADAM_SANDY_CLOAK         FORMS_START + 154
#define SPECIES_WORMADAM_TRASH_CLOAK         FORMS_START + 155

// Cherrim
#define SPECIES_CHERRIM_SUNSHINE             FORMS_START + 156

// Shellos
#define SPECIES_SHELLOS_EAST_SEA             FORMS_START + 157

// Gastrodon
#define SPECIES_GASTRODON_EAST_SEA           FORMS_START + 158

// Rotom
#define SPECIES_ROTOM_HEAT                   FORMS_START + 159
#define SPECIES_ROTOM_WASH                   FORMS_START + 160
#define SPECIES_ROTOM_FROST                  FORMS_START + 161
#define SPECIES_ROTOM_FAN                    FORMS_START + 162
#define SPECIES_ROTOM_MOW                    FORMS_START + 163

// Origin Forme
#define SPECIES_DIALGA_ORIGIN                FORMS_START + 164
#define SPECIES_PALKIA_ORIGIN                FORMS_START + 165
#define SPECIES_GIRATINA_ORIGIN              FORMS_START + 166

// Shaymin
#define SPECIES_SHAYMIN_SKY                  FORMS_START + 167

// Arceus
#define SPECIES_ARCEUS_FIGHTING              FORMS_START + 168
#define SPECIES_ARCEUS_FLYING                FORMS_START + 169
#define SPECIES_ARCEUS_POISON                FORMS_START + 170
#define SPECIES_ARCEUS_GROUND                FORMS_START + 171
#define SPECIES_ARCEUS_ROCK                  FORMS_START + 172
#define SPECIES_ARCEUS_BUG                   FORMS_START + 173
#define SPECIES_ARCEUS_GHOST                 FORMS_START + 174
#define SPECIES_ARCEUS_STEEL                 FORMS_START + 175
#define SPECIES_ARCEUS_FIRE                  FORMS_START + 176
#define SPECIES_ARCEUS_WATER                 FORMS_START + 177
#define SPECIES_ARCEUS_GRASS                 FORMS_START + 178
#define SPECIES_ARCEUS_ELECTRIC              FORMS_START + 179
#define SPECIES_ARCEUS_PSYCHIC               FORMS_START + 180
#define SPECIES_ARCEUS_ICE                   FORMS_START + 181
#define SPECIES_ARCEUS_DRAGON                FORMS_START + 182
#define SPECIES_ARCEUS_DARK                  FORMS_START + 183
#define SPECIES_ARCEUS_FAIRY                 FORMS_START + 184

// Basculin
#define SPECIES_BASCULIN_BLUE_STRIPED        FORMS_START + 185
#define SPECIES_BASCULIN_WHITE_STRIPED       FORMS_START + 186

// Darmanitan
#define SPECIES_DARMANITAN_ZEN_MODE          FORMS_START + 187
#define SPECIES_DARMANITAN_ZEN_MODE_GALARIAN FORMS_START + 188

// Deerling
#define SPECIES_DEERLING_SUMMER              FORMS_START + 189
#define SPECIES_DEERLING_AUTUMN              FORMS_START + 190
#define SPECIES_DEERLING_WINTER              FORMS_START + 191

// Sawsbuck
#define SPECIES_SAWSBUCK_SUMMER              FORMS_START + 192
#define SPECIES_SAWSBUCK_AUTUMN              FORMS_START + 193
#define SPECIES_SAWSBUCK_WINTER              FORMS_START + 194

// Therian Forms
#define SPECIES_TORNADUS_THERIAN             FORMS_START + 195
#define SPECIES_THUNDURUS_THERIAN            FORMS_START + 196
#define SPECIES_LANDORUS_THERIAN             FORMS_START + 197
#define SPECIES_ENAMORUS_THERIAN             FORMS_START + 198

// Kyurem
#define SPECIES_KYUREM_WHITE                 FORMS_START + 199
#define SPECIES_KYUREM_BLACK                 FORMS_START + 200

// Keldeo
#define SPECIES_KELDEO_RESOLUTE              FORMS_START + 201

// Meloetta
#define SPECIES_MELOETTA_PIROUETTE           FORMS_START + 202

// Genesect
#define SPECIES_GENESECT_DOUSE_DRIVE         FORMS_START + 203
#define SPECIES_GENESECT_SHOCK_DRIVE         FORMS_START + 204
#define SPECIES_GENESECT_BURN_DRIVE          FORMS_START + 205
#define SPECIES_GENESECT_CHILL_DRIVE         FORMS_START + 206

// Greninja
#define SPECIES_GRENINJA_BATTLE_BOND         FORMS_START + 207
#define SPECIES_GRENINJA_ASH                 FORMS_START + 208

// Vivillon
#define SPECIES_VIVILLON_POLAR               FORMS_START + 209
#define SPECIES_VIVILLON_TUNDRA              FORMS_START + 210
#define SPECIES_VIVILLON_CONTINENTAL         FORMS_START + 211
#define SPECIES_VIVILLON_GARDEN              FORMS_START + 212
#define SPECIES_VIVILLON_ELEGANT             FORMS_START + 213
#define SPECIES_VIVILLON_MEADOW              FORMS_START + 214
#define SPECIES_VIVILLON_MODERN              FORMS_START + 215
#define SPECIES_VIVILLON_MARINE              FORMS_START + 216
#define SPECIES_VIVILLON_ARCHIPELAGO         FORMS_START + 217
#define SPECIES_VIVILLON_HIGH_PLAINS         FORMS_START + 218
#define SPECIES_VIVILLON_SANDSTORM           FORMS_START + 219
#define SPECIES_VIVILLON_RIVER               FORMS_START + 220
#define SPECIES_VIVILLON_MONSOON             FORMS_START + 221
#define SPECIES_VIVILLON_SAVANNA             FORMS_START + 222
#define SPECIES_VIVILLON_SUN                 FORMS_START + 223
#define SPECIES_VIVILLON_OCEAN               FORMS_START + 224
#define SPECIES_VIVILLON_JUNGLE              FORMS_START + 225
#define SPECIES_VIVILLON_FANCY               FORMS_START + 226
#define SPECIES_VIVILLON_POKE_BALL           FORMS_START + 227

// Flabébé
#define SPECIES_FLABEBE_YELLOW_FLOWER        FORMS_START + 228
#define SPECIES_FLABEBE_ORANGE_FLOWER        FORMS_START + 229
#define SPECIES_FLABEBE_BLUE_FLOWER          FORMS_START + 230
#define SPECIES_FLABEBE_WHITE_FLOWER         FORMS_START + 231

// Floette
#define SPECIES_FLOETTE_YELLOW_FLOWER        FORMS_START + 232
#define SPECIES_FLOETTE_ORANGE_FLOWER        FORMS_START + 233
#define SPECIES_FLOETTE_BLUE_FLOWER          FORMS_START + 234
#define SPECIES_FLOETTE_WHITE_FLOWER         FORMS_START + 235
#define SPECIES_FLOETTE_ETERNAL_FLOWER       FORMS_START + 236

// Florges
#define SPECIES_FLORGES_YELLOW_FLOWER        FORMS_START + 237
#define SPECIES_FLORGES_ORANGE_FLOWER        FORMS_START + 238
#define SPECIES_FLORGES_BLUE_FLOWER          FORMS_START + 239
#define SPECIES_FLORGES_WHITE_FLOWER         FORMS_START + 240

// Furfrou
#define SPECIES_FURFROU_HEART_TRIM           FORMS_START + 241
#define SPECIES_FURFROU_STAR_TRIM            FORMS_START + 242
#define SPECIES_FURFROU_DIAMOND_TRIM         FORMS_START + 243
#define SPECIES_FURFROU_DEBUTANTE_TRIM       FORMS_START + 244
#define SPECIES_FURFROU_MATRON_TRIM          FORMS_START + 245
#define SPECIES_FURFROU_DANDY_TRIM           FORMS_START + 246
#define SPECIES_FURFROU_LA_REINE_TRIM        FORMS_START + 247
#define SPECIES_FURFROU_KABUKI_TRIM          FORMS_START + 248
#define SPECIES_FURFROU_PHARAOH_TRIM         FORMS_START + 249

// Meowstic
#define SPECIES_MEOWSTIC_FEMALE              FORMS_START + 250

// Aegislash
#define SPECIES_AEGISLASH_BLADE              FORMS_START + 251

// Pumpkaboo
#define SPECIES_PUMPKABOO_SMALL              FORMS_START + 252
#define SPECIES_PUMPKABOO_LARGE              FORMS_START + 253
#define SPECIES_PUMPKABOO_SUPER              FORMS_START + 254

// Gourgeist
#define SPECIES_GOURGEIST_SMALL              FORMS_START + 255
#define SPECIES_GOURGEIST_LARGE              FORMS_START + 256
#define SPECIES_GOURGEIST_SUPER              FORMS_START + 257

// Xerneas
#define SPECIES_XERNEAS_ACTIVE               FORMS_START + 258

// Zygarde
#define SPECIES_ZYGARDE_10                   FORMS_START + 259
#define SPECIES_ZYGARDE_10_POWER_CONSTRUCT   FORMS_START + 260
#define SPECIES_ZYGARDE_50_POWER_CONSTRUCT   FORMS_START + 261
#define SPECIES_ZYGARDE_COMPLETE             FORMS_START + 262

// Hoopa
#define SPECIES_HOOPA_UNBOUND                FORMS_START + 263

// Oricorio
#define SPECIES_ORICORIO_POM_POM             FORMS_START + 264
#define SPECIES_ORICORIO_PAU                 FORMS_START + 265
#define SPECIES_ORICORIO_SENSU               FORMS_START + 266

// Rockruff
#define SPECIES_ROCKRUFF_OWN_TEMPO           FORMS_START + 267

// Lycanroc
#define SPECIES_LYCANROC_MIDNIGHT            FORMS_START + 268
#define SPECIES_LYCANROC_DUSK                FORMS_START + 269

// Wishiwashi
#define SPECIES_WISHIWASHI_SCHOOL            FORMS_START + 270

// Silvally
#define SPECIES_SILVALLY_FIGHTING            FORMS_START + 271
#define SPECIES_SILVALLY_FLYING              FORMS_START + 272
#define SPECIES_SILVALLY_POISON              FORMS_START + 273
#define SPECIES_SILVALLY_GROUND              FORMS_START + 274
#define SPECIES_SILVALLY_ROCK                FORMS_START + 275
#define SPECIES_SILVALLY_BUG                 FORMS_START + 276
#define SPECIES_SILVALLY_GHOST               FORMS_START + 277
#define SPECIES_SILVALLY_STEEL               FORMS_START + 278
#define SPECIES_SILVALLY_FIRE                FORMS_START + 279
#define SPECIES_SILVALLY_WATER               FORMS_START + 280
#define SPECIES_SILVALLY_GRASS               FORMS_START + 281
#define SPECIES_SILVALLY_ELECTRIC            FORMS_START + 282
#define SPECIES_SILVALLY_PSYCHIC             FORMS_START + 283
#define SPECIES_SILVALLY_ICE                 FORMS_START + 284
#define SPECIES_SILVALLY_DRAGON              FORMS_START + 285
#define SPECIES_SILVALLY_DARK                FORMS_START + 286
#define SPECIES_SILVALLY_FAIRY               FORMS_START + 287

// Minior
#define SPECIES_MINIOR_METEOR_ORANGE         FORMS_START + 288
#define SPECIES_MINIOR_METEOR_YELLOW         FORMS_START + 289
#define SPECIES_MINIOR_METEOR_GREEN          FORMS_START + 290
#define SPECIES_MINIOR_METEOR_BLUE           FORMS_START + 291
#define SPECIES_MINIOR_METEOR_INDIGO         FORMS_START + 292
#define SPECIES_MINIOR_METEOR_VIOLET         FORMS_START + 293
#define SPECIES_MINIOR_CORE_RED              FORMS_START + 294
#define SPECIES_MINIOR_CORE_ORANGE           FORMS_START + 295
#define SPECIES_MINIOR_CORE_YELLOW           FORMS_START + 296
#define SPECIES_MINIOR_CORE_GREEN            FORMS_START + 297
#define SPECIES_MINIOR_CORE_BLUE             FORMS_START + 298
#define SPECIES_MINIOR_CORE_INDIGO           FORMS_START + 299
#define SPECIES_MINIOR_CORE_VIOLET           FORMS_START + 300

// Mimikyu
#define SPECIES_MIMIKYU_BUSTED               FORMS_START + 301

// Necrozma
#define SPECIES_NECROZMA_DUSK_MANE           FORMS_START + 302
#define SPECIES_NECROZMA_DAWN_WINGS          FORMS_START + 303
#define SPECIES_NECROZMA_ULTRA               FORMS_START + 304

// Magearna
#define SPECIES_MAGEARNA_ORIGINAL_COLOR      FORMS_START + 305

// Cramorant
#define SPECIES_CRAMORANT_GULPING            FORMS_START + 306
#define SPECIES_CRAMORANT_GORGING            FORMS_START + 307

// Toxtricity
#define SPECIES_TOXTRICITY_LOW_KEY           FORMS_START + 308

// Sinistea
#define SPECIES_SINISTEA_ANTIQUE             FORMS_START + 309

// Polteageist
#define SPECIES_POLTEAGEIST_ANTIQUE          FORMS_START + 310

// Alcremie
#define SPECIES_ALCREMIE_RUBY_CREAM          FORMS_START + 311
#define SPECIES_ALCREMIE_MATCHA_CREAM        FORMS_START + 312
#define SPECIES_ALCREMIE_MINT_CREAM          FORMS_START + 313
#define SPECIES_ALCREMIE_LEMON_CREAM         FORMS_START + 314
#define SPECIES_ALCREMIE_SALTED_CREAM        FORMS_START + 315
#define SPECIES_ALCREMIE_RUBY_SWIRL          FORMS_START + 316
#define SPECIES_ALCREMIE_CARAMEL_SWIRL       FORMS_START + 317
#define SPECIES_ALCREMIE_RAINBOW_SWIRL       FORMS_START + 318

// Eiscue
#define SPECIES_EISCUE_NOICE_FACE            FORMS_START + 319

// Indeedee
#define SPECIES_INDEEDEE_FEMALE              FORMS_START + 320

// Morpeko
#define SPECIES_MORPEKO_HANGRY               FORMS_START + 321

// Zacian
#define SPECIES_ZACIAN_CROWNED_SWORD         FORMS_START + 322

// Zamazenta
#define SPECIES_ZAMAZENTA_CROWNED_SHIELD     FORMS_START + 323

// Eternatus
#define SPECIES_ETERNATUS_ETERNAMAX          FORMS_START + 324

// Urshifu
#define SPECIES_URSHIFU_RAPID_STRIKE_STYLE   FORMS_START + 325

// Zarude
#define SPECIES_ZARUDE_DADA                  FORMS_START + 326

// Calyrex
#define SPECIES_CALYREX_ICE_RIDER            FORMS_START + 327
#define SPECIES_CALYREX_SHADOW_RIDER         FORMS_START + 328

#define FORMS_START SPECIES_ENAMORUS
#define SPECIES_EGG SPECIES_CALYREX_SHADOW_RIDER + 1 

#define NUM_SPECIES SPECIES_EGG + 1

#endif  // GUARD_CONSTANTS_SPECIES_H
